spring.datasource.url=jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=require&channelBinding=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXP}

# Razorpay
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# Cloudflare Stream
cloudflare.account-id=${CLOUDFLARE_ACCOUNT_ID}
cloudflare.api-token=${CLOUDFLARE_API_TOKEN}
cloudflare.api-base-url=${CLOUDFLARE_API_BASE_URL}
cloudflare.customer-subdomain=${CLOUDFLARE_CUSTOMER_SUBDOMAIN}

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB